seed: 50

data:
    raw_path: "datasets/zipf/raw/"
    processed_path: "datasets/zipf/processed/"
    output_path: "outputs/"

vocab:
    tokenizer: "word-en"
    output_path: "char-en"
    size: 10000
    min_freq: -1

    spm:
        output_path: ""
        model_type: bpe
        model_name: spm

